import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/header/header";
import { Toaster } from "@/components/ui/toaster";
import userGet from "@/actions/user-get";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { ok } = await userGet();

  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
        <Toaster active={false} />
      </body>
    </html>
  );
}
